# Dockerizing HAProxy Load Balancing
# https://github.com/jbobos/docker-haproxy
#
version: '3.1'
services:
  web:
    image: nginx:1.17.3-alpine

  proxy:
    image: myproxy:1.0.0-alpine
    container_name: proxy
    ports:
      - 8000:80
    environment:
      - WEB_SERVER_NUM=5
      - WEB_SERVER_HOST=web
      - WEB_SERVER_PORT=80
      - DNS_SERVER_HOST=127.0.0.11
      - DNS_SERVER_PORT=53
    restart: always
    build:
      context: ./proxy/
    depends_on:
      - web

